# Ref: https://github.com/doomemacs/doomemacs
# [".config/emacs"]
# type = "git-repo"
# url = "https://github.com/doomemacs/doomemacs"
# clone.args = ["--depth", "1"]

# Ref: https://github.com/yazi-rs/plugins
# [".config/yazi/plugins"]
# type = "archive"
# url = "https://github.com/yazi-rs/plugins/archive/refs/heads/main.tar.gz"
# stripComponents = 1
# include = ["*/full-border.yazi/**"]
# refreshPeriod = "672h" # 4w

# Ref: https://github.com/imsi32/yatline.yazi
# [".config/yazi/plugins/yatline.yazi"]
# type = "archive"
# url = "https://github.com/imsi32/yatline.yazi/archive/refs/heads/main.tar.gz"
# stripComponents = 1
# refreshPeriod = "672h" # 4w

{{- if (ne .chezmoi.config.data.hosttype "darwin") }}

# Ref: https://github.com/ryanoasis/nerd-fonts
[".local/share/fonts/nerd-fonts-jetbrains-mono"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.tar.xz"
exact = true

{{- end }}

# Ref: https://github.com/z-shell/zsh-eza
[".oh-my-zsh/custom/plugins/zsh-eza"]
type = "archive"
url = "https://github.com/z-shell/zsh-eza/archive/refs/heads/main.tar.gz"
stripComponents = 1
exact = true
refreshPeriod = "672h" # 4w

# Ref: https://github.com/MichaelAquilina/zsh-you-should-use
[".oh-my-zsh/custom/plugins/zsh-you-should-use"]
type = "archive"
url = "https://github.com/MichaelAquilina/zsh-you-should-use/archive/refs/heads/master.tar.gz"
stripComponents = 1
exact = true
refreshPeriod = "672h" # 4w

# Ref: https://github.com/gpakosz/.tmux
[".tmux"]
type = "archive"
url = "https://github.com/gpakosz/.tmux/archive/refs/heads/master.tar.gz"
stripComponents = 1
exact = true
refreshPeriod = "672h" # 4w

# Ref: https://github.com/amix/vimrc
[".vim_runtime"]
type = "archive"
url = "https://github.com/amix/vimrc/archive/refs/heads/master.tar.gz"
stripComponents = 1
exact = true
refreshPeriod = "672h" # 4w
