[theme]
name = "gruvbox-dark"

[icons]
name = "material-nf"

[[block]]
block = "music"
buttons = ["play", "next"]

[[block]]
block = "backlight"

[[block]]
block = "temperature"
interval = 5

[[block]]
block = "memory"
interval = 5
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 2

[[block]]
block = "custom"
command = ''' echo "{\"icon\":\"net_vpn\",\"state\":\"Info\",\"text\":\"$(curl -sS -m5 -f https://am.i.mullvad.net/country || echo -1)\"}" '''
json = true
interval = 150

[[block]]
block = "net"
format_alt = "{ssid} {signal_strength}"
interval = 2

[[block]]
block = "sound"
max_vol = 100
device_kind = "source"

[[block]]
block = "sound"
max_vol = 100

[[block]]
block = "battery"
interval = 10
format = "{percentage} ({power})"

[[block]]
block = "time"
interval = 5
