[open]
prepend_rules = [
  # Media
  { mime = "{audio,video}/*", use = [ "open", "reveal" ] },
]

[plugin]
prepend_previewers = [
  # Audio
  { mime = "audio/*", run = "mediainfo" },
  # Image
  { mime = "image/*", run = "mediainfo" },
  # Video
  { mime = "video/*", run = "mediainfo" },
  # PDF
  { mime = "application/pdf", run = "pdfinfo" },
  # Archive
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", run = "ouch" },
  # Font
  { mime = "font/*", run = "exiftool" },
  { mime = "application/ms-opentype", run = "exiftool" },
  # Other
  { mime = "application/bittorrent", run = "aria2c" },
  { mime = "application/sqlite3", run = "sqlite3" },
  { mime = "application/x-executable", run = "readelf" },
  { mime = "application/x-pie-executable", run = "readelf" },
]

prepend_preloaders = [
  # Image
  { mime = "image/*", run = "noop" },
  # Video
  { mime = "video/*", run = "noop" },
  # PDF
  { mime = "application/pdf", run = "noop" },
  # Font
  { mime = "font/*", run = "noop" },
]
